const dialog=document.querySelector('#audit-dialog');
document.addEventListener('click',e=>{if(e.target.closest('[data-audit]')){document.querySelector('.form-result').hidden=true;dialog.showModal();}});
document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());
dialog?.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
document.querySelector('#audit-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const content=`ЗАПРОС НА ВНЕДРЕНИЕ КОНТРОЛЯ VERITY\n\nКомпания: ${d.get('company')}\nEmail: ${d.get('email')}\nСценарий: ${d.get('scenario')}\n\nЦель: подключить агента к данным и инструментам через единый контур прав, проверок и трассировки.\nСогласовать до пилота: выборку, источники, режим, критерии результата, сроки и стоимость.\n\nПодготовлено в демонстрационном прототипе. Данные не отправлены.\n`;const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='verity-integration-request.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('.form-result').hidden=false;});
const menu=document.querySelector('.menu-toggle');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',!open);menu.setAttribute('aria-label',open?'Открыть меню':'Закрыть меню');document.querySelector('#main-nav').classList.toggle('open',!open);});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','Открыть меню');document.querySelector('#main-nav').classList.remove('open');}));
document.querySelectorAll('.motion-toggle').forEach(b=>b.addEventListener('click',()=>{const paused=document.body.classList.toggle('motion-paused');document.querySelectorAll('.motion-toggle').forEach(btn=>{btn.setAttribute('aria-pressed',paused);btn.setAttribute('aria-label',paused?'Включить анимацию':'Приостановить анимацию');btn.innerHTML=`<span aria-hidden="true">${paused?'▷':'Ⅱ'}</span>`;});}));
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const targets=document.querySelectorAll('.pain-row,.audience-grid>article,.pilot-content,.explain-step');targets.forEach(el=>el.classList.add('reveal'));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target);}}),{threshold:.08});targets.forEach(el=>observer.observe(el));document.documentElement.classList.add('motion-ready');}
// Every execution below is a local demonstration, with no external API calls.
const gateway=document.querySelector('[data-gateway]');
if(gateway){
 const cases={price:{intent:'crm.delete_records',source:'CRM API',policy:'scope: crm.read',rule:'allowed_scopes: [crm.read]',outcome:'block',title:'Действие остановлено',description:'Агенту разрешено чтение. Права на удаление записей нет.',trace:'deny: missing_permission',sourceLog:'connector: CRM / доступен'},good:{intent:'crm.read_summary',source:'CRM API',policy:'scope: crm.read',rule:'allowed_scopes: [crm.read]',outcome:'allow',title:'Запрос разрешён',description:'Инструмент доступен. Операция чтения соответствует политике.',trace:'allow: scope_matched',sourceLog:'connector: CRM / доступен'},offline:{intent:'«Проект согласован»',source:'Docs: timeout',policy:'grounding: required',rule:'require: source_confirmation',outcome:'human',title:'Нужен человек',description:'Источник не ответил. Утверждение нельзя считать подтверждённым.',trace:'escalate: unverified_claim',sourceLog:'connector: Docs / недоступен'}};
 const descriptions=[{type:'ВАШ АГЕНТ',title:'Передать намерение и контекст',copy:'Агент формирует запрос или ответ. В контур поступают его идентичность, контекст пользователя и выбранное действие. Это вход для проверки, а не разрешение на выполнение.',io:'agent + user_context + intent → запрос в шлюз'},{type:'ЕДИНЫЙ ВХОД',title:'Подключить через общий интерфейс',copy:'Проектируем API и SDK, через которые агент передаёт запросы в единый контур. Здесь определяется контекст вызова; конкретный протокол и авторизация согласуются в пилоте.',io:'запрос агента → нормализованный контекст'},{type:'ШЛЮЗ ИНТЕГРАЦИЙ',title:'Получить доступ к данным и tools',copy:'Контур связывает запрос с подключённым инструментом или источником. Для проверяемых утверждений получает основания; фиксирует результат, ошибку или недоступность.',io:'контекст + connector → данные / доступный инструмент / ошибка'},{type:'ШЛЮЗ ПОЛИТИК',title:'Проверить право и условия',copy:'Применяем права на операцию, требования к источникам и правила одобрения. В демо доступ к чтению CRM не разрешает удалять записи. Отсутствие подтверждения не считается успешной проверкой.',io:'запрос + scopes + policy → allow / deny / requires_review'},{type:'ШЛЮЗ РЕШЕНИЙ',title:'Применить результат проверки',copy:'До выполнения — пропустить выбранный запрос, остановить или запросить человека. После события — зафиксировать результат и передать на разбор. История остаётся в общей трассе.',io:'вердикт + режим → маршрут + запись в трассу'}];
 const tabs=[...gateway.querySelectorAll('[data-case]')],nodes=[...gateway.querySelectorAll('[data-step]')];
 const run=gateway.querySelector('[data-run]'),inspector=gateway.querySelector('.gateway-inspector');
 let selected='price',busy=false;
 const mode=()=>document.querySelector('input[name="check-mode"]:checked')?.value||'before';
 function updateCase(key){selected=key;const c=cases[key];gateway.dataset.state='idle';tabs.forEach(t=>{const on=t.dataset.case===key;t.setAttribute('aria-selected',on);t.tabIndex=on?0:-1;});gateway.querySelector('[role="tabpanel"]').setAttribute('aria-labelledby','case-'+key);gateway.querySelector('[data-agent-intent]').textContent=c.intent;gateway.querySelector('[data-source-label]').textContent=c.source;gateway.querySelector('[data-policy-label]').textContent=c.policy;gateway.querySelector('[data-log-answer]').textContent=c.intent;gateway.querySelector('[data-log-source]').textContent=c.sourceLog;gateway.querySelector('.log-fields>div:nth-child(3) code').textContent=c.rule;gateway.querySelector('[data-log-verdict]').textContent='ожидает проверки';gateway.querySelector('[data-result-title]').textContent='Запрос готов к проверке';gateway.querySelector('[data-result-copy]').textContent='Пройдите интеграцию, политику и решение.';gateway.querySelector('.run-text').textContent='Запустить проверку';nodes.forEach(n=>n.classList.remove('is-current','is-done'));gateway.querySelectorAll('.outcome').forEach(o=>o.classList.remove('is-selected'));}
 function inspect(index){nodes.forEach(n=>n.setAttribute('aria-expanded',Number(n.dataset.step)===index));const d=descriptions[index];inspector.hidden=false;inspector.querySelector('[data-inspector-type]').textContent=d.type;inspector.querySelector('[data-inspector-title]').textContent=d.title;inspector.querySelector('[data-inspector-copy]').textContent=d.copy;inspector.querySelector('[data-inspector-io]').textContent=d.io;}
 nodes.forEach((node,i)=>{node.addEventListener('click',()=>inspect(i));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(i);}});});
 gateway.querySelector('[data-close-inspector]').addEventListener('click',()=>{const open=nodes.find(n=>n.getAttribute('aria-expanded')==='true');inspector.hidden=true;nodes.forEach(n=>n.setAttribute('aria-expanded','false'));open?.focus();});
 tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{if(!busy)updateCase(tab.dataset.case);});tab.addEventListener('keydown',e=>{if(busy)return;let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();updateCase(tabs[next].dataset.case);tabs[next].focus();}});});
 run.addEventListener('click',async()=>{if(busy)return;busy=true;updateCase(selected);gateway.dataset.state='running';run.disabled=true;tabs.forEach(t=>t.disabled=true);document.querySelectorAll('[name="check-mode"]').forEach(r=>r.disabled=true);gateway.querySelector('.run-text').textContent='Проверяем…';const stages=['Получаем запрос агента','Готовим контекст вызова','Определяем источник и инструмент','Применяем политику','Выбираем маршрут'];const fast=matchMedia('(prefers-reduced-motion: reduce)').matches;for(let i=0;i<nodes.length;i++){nodes.forEach(n=>n.classList.remove('is-current'));nodes[i].classList.add('is-current');gateway.querySelector('[data-result-title]').textContent=stages[i];gateway.querySelector('[data-result-copy]').textContent='Демонстрационное выполнение';await new Promise(resolve=>setTimeout(resolve,fast?0:550));nodes[i].classList.remove('is-current');nodes[i].classList.add('is-done');}const c=cases[selected],after=mode()==='after',outcome=after&&c.outcome==='block'?'human':c.outcome;gateway.dataset.state=outcome;gateway.querySelector(`[data-outcome="${outcome}"]`).classList.add('is-selected');gateway.querySelector('[data-result-title]').textContent=after?(c.outcome==='allow'?'Нарушение не выявлено':'Событие требует разбора'):c.title;gateway.querySelector('[data-result-copy]').textContent=after?c.description+' Событие уже произошло; этот режим его не останавливает.':c.description;gateway.querySelector('[data-log-verdict]').textContent=after?'audit: '+c.trace:c.trace;run.disabled=false;tabs.forEach(t=>t.disabled=false);document.querySelectorAll('[name="check-mode"]').forEach(r=>r.disabled=false);gateway.querySelector('.run-text').textContent='Повторить проверку';busy=false;});
 document.querySelectorAll('[name="check-mode"]').forEach(r=>r.addEventListener('change',()=>{const after=mode()==='after';document.querySelector('#mode-description').textContent=after?'Событие уже произошло. Режим фиксирует результат проверки и передаёт нарушения на разбор.':'Запрос проходит проверки до выполнения. Нужна точка перехвата перед вызовом инструмента или отправкой ответа.';gateway.querySelector('.canvas-tag').textContent=after?'Демо · после события':'Демо · до выполнения';gateway.querySelector('.outcome.allow strong').textContent=after?'Подтвердить':'Пропустить';gateway.querySelector('.outcome.block strong').textContent=after?'Недоступно в этом режиме':'Остановить';gateway.querySelector('.outcome.human strong').textContent=after?'Передать на разбор':'Передать человеку';updateCase(selected);}));
}

// Independent verification: source-backed examples, simulated entirely locally.
const verification = document.querySelector('[data-verification]');
if (verification) {
 const examples = {
  evidence: {intentLabel:'Сформировал ответ', intent:'«Договор согласован. Можно начинать работу»', risk:'Если отправить сразу: предположение станет основанием для действия.', source:'Диадок · карточка договора', value:'Статус: на согласовании', extra:'Подпись ответственного отсутствует.', rule:'Утверждение «согласован» требует подтверждения в системе.', code:'evidence_missing', icon:'↗', title:'Передать человеку', result:'Не отправлять неподтверждённый ответ. Запросить решение ответственного.', reply:'«Согласование не подтверждено. Дождитесь решения ответственного».', verdict:'Ответ удержан: согласование не подтверждено источником.'},
  conflict: {intentLabel:'Использовал старый контекст', intent:'«Срок проекта — 15 октября»', risk:'Если отправить сразу: команда начнёт планировать по устаревшей версии.', source:'Битрикс24 · документ и план', value:'Черновик: 15.10 → план: 22.10', extra:'Утверждённый план новее черновика. Версии расходятся.', rule:'Приоритет — актуальному утверждённому источнику. Исправленный ответ проверяется снова.', code:'source_conflict', icon:'↻', title:'Вернуть на доработку', result:'Передать агенту расхождение и актуальный источник. Удержать отправку до повторной проверки.', reply:'«Используй утверждённый план: 22 октября. Добавь ссылку на источник».', verdict:'Конфликт найден: агент получил источник для доработки. Ответ ещё не отправлен.'},
  permission: {intentLabel:'Запросил вызов инструмента', intent:'documents.share(folder, "public")', risk:'Если выполнить сразу: внутренние документы получат публичный доступ.', source:'Политика · доступ к документам', value:'Разрешено: documents.read', extra:'Публикация не входит в права этого агента.', rule:'Перед каждым защищённым действием сравниваем операцию с разрешениями агента.', code:'permission_denied', icon:'⊣', title:'Остановить действие', result:'Заблокировать вызов до выполнения. Документы остаются закрытыми.', reply:'«Публикация запрещена текущей политикой. Причина записана в журнал».', verdict:'Действие заблокировано до выполнения: право на публикацию отсутствует.'}
 };
 const fields = {'intent-label':'intentLabel',intent:'intent',risk:'risk','source-name':'source','source-value':'value','source-extra':'extra',rule:'rule','result-icon':'icon','result-title':'title','result-copy':'result',reply:'reply'};
 const tabs = [...verification.querySelectorAll('[data-verify-case]')];
 const run = verification.querySelector('[data-verify-run]');
 let current = 'evidence', generation = 0;
 function selectCase(key) {
  generation++; current = key; verification.dataset.phase = 'idle'; verification.dataset.example = key;
  tabs.forEach(tab => {const on = tab.dataset.verifyCase === key; tab.setAttribute('aria-selected',on); tab.tabIndex = on ? 0 : -1;});
  verification.querySelector('[role=tabpanel]').setAttribute('aria-labelledby','verify-'+key);
  Object.entries(fields).forEach(([selector,field]) => verification.querySelector('[data-verify-'+selector+']').textContent = examples[key][field]);
  verification.querySelector('[data-verify-code]').textContent = 'Ожидает запуска';
  verification.querySelector('[data-verify-status]').textContent = 'Пример: '+tabs.find(t=>t.dataset.verifyCase===key).textContent.trim()+'. Запустите проверку.';
  verification.querySelector('[data-verify-run-label]').textContent = 'Показать проверку'; run.disabled = false;
 }
 tabs.forEach((tab,i) => {
  tab.addEventListener('click',()=>selectCase(tab.dataset.verifyCase));
  tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectCase(tabs[next].dataset.verifyCase);tabs[next].focus();}});
 });
 run.addEventListener('click',async()=>{
  const token=++generation; const example=examples[current]; run.disabled=true;
  verification.querySelector('[data-verify-run-label]').textContent='Проверяем…';
  const phases=[['request','Получаем ответ или действие агента.','request_received'],['source','Обращаемся к источнику, независимому от ответа агента.','source_received'],['check','Сопоставляем данные и применяем правило.','checking_policy']];
  const instant=matchMedia('(prefers-reduced-motion: reduce)').matches;
  for(const [phase,status,code] of phases){
   if(token!==generation)return;
   verification.dataset.phase=phase;verification.querySelector('[data-verify-status]').textContent=status;verification.querySelector('[data-verify-code]').textContent=code;
   await new Promise(resolve=>setTimeout(resolve,instant?0:1000));
  }
  if(token!==generation)return;
  verification.dataset.phase='done';verification.querySelector('[data-verify-code]').textContent=example.code;
  verification.querySelector('[data-verify-status]').textContent=example.verdict;
  verification.querySelector('[data-verify-run-label]').textContent='Повторить пример';run.disabled=false;
 });
 selectCase(current);
}
const integrationPause=document.querySelector('[data-integration-pause]');
integrationPause?.addEventListener('click',()=>{const paused=document.querySelector('#integrations').classList.toggle('is-paused');integrationPause.setAttribute('aria-pressed',paused);integrationPause.innerHTML=paused?'▷ <span>Включить движение</span>':'Ⅱ <span>Остановить движение</span>';});
